org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/XtextWebDocumentAccess.xtend
org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/XtextWebDocumentAccess.java

Signed-off-by: Franz Becker <franz.becker@itemis.de>

[Bug 490284] extract creation of ReadAccess into an overridable method

---

org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java

[495851] #5 made FormatterPreferences injection optional

#5 made FormatterPreferences injection optional

---

gradle/eclipse-project-layout.gradle
gradle/java-compiler-settings.gradle
org.eclipse.xtext.web.example.jetty/build.gradle
org.eclipse.xtext.web.servlet/build.gradle
org.eclipse.xtext.web/build.gradle
org.eclipse.xtext.xbase.web/build.gradle

Consistent use of tabs instead of spaces
Use single whitespace between brackets

[format] Streamlined whitespaces

---

org.eclipse.xtext.web.example.entities.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.web.example.entities/META-INF/MANIFEST.MF

[502879] Streamlined plugin metadata

---

org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
org.eclipse.xtext.web/src/main/js/xtext/xtext-orion.js

Use EditorContext.showMarkers to report problems to orion.
this way Listeners to the ValidationService get notified about the problems.
Fixes #13

Use EditorContext.showMarkers to report problems to orion.

---

org.eclipse.xtext.web.example.entities.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.web.example.entities/.launch/Generate Language Infrastructure (org.eclipse.xtext.idea.example.entities).launch
org.eclipse.xtext.web.example.entities/META-INF/MANIFEST.MF
org.eclipse.xtext.web.example.entities/plugin.xml
org.eclipse.xtext.web.example.entities/plugin.xml_gen

Signed-off-by: Karsten Thoms karsten.thoms@itemis.de

Fixed copy/paste error 'idea' -> 'web'

---

.gitignore
.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.example.entities.ide/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.example.entities/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.example.jetty/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.example.statemachine.ide/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.example.statemachine/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web.servlet/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.web/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xbase.web/.settings/org.eclipse.buildship.core.prefs

connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship

Gradle composite

---

org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java

[501975] Null guard for switch statements

---

org.eclipse.xtext.web.example.jetty/.classpath
org.eclipse.xtext.web.example.jetty/.gitignore
org.eclipse.xtext.web.servlet/.classpath
org.eclipse.xtext.web.servlet/.gitignore
org.eclipse.xtext.web/.classpath
org.eclipse.xtext.web/.gitignore
org.eclipse.xtext.xbase.web/.classpath
org.eclipse.xtext.xbase.web/.gitignore

added missing .classpath files

added missing .classpath files

---

org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java

Replace deprecated indentationLength by tabWidth

---

build.gradle
gradle/bootstrap-setup.gradle
gradle/default-project-layout.gradle
gradle/eclipse-project-layout.gradle
gradle/xtend-compiler-settings.gradle

* Use build result from xtend-bootstrap job for Xtend compiler
* Added `skipXtendCompiler` option

Improve Xtend bootstrap

---

org.eclipse.xtext.web/src/main/js/xtext/xtext-codemirror.js

[#31] Updated documentation on formatting in CodeMirror

---

org.eclipse.xtext.web/build.gradle

updated com.moowork.node dependency #33

---

.project
org.eclipse.xtext.web.example.entities.ide/.project
org.eclipse.xtext.web.example.entities/.project
org.eclipse.xtext.web.example.jetty/.project
org.eclipse.xtext.web.example.statemachine.ide/.project
org.eclipse.xtext.web.example.statemachine/.project
org.eclipse.xtext.web.servlet/.project
org.eclipse.xtext.web/.project
org.eclipse.xtext.xbase.web/.project

gradleprojectbuilder added by Buildship project import

---

org.eclipse.xtext.web.example.entities.ide/.project
org.eclipse.xtext.web.example.entities/.project
org.eclipse.xtext.web.example.statemachine.ide/.project
org.eclipse.xtext.web.example.statemachine/.project

removed duplicate builders

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/AbstractWebServerTest.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/Bug489571Test.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ContentAssistTest.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/Formatting1Test.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/GeneratorTest.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/OccurrenceTest.xtend
org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/AbstractXbaseWebTest.xtend
org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/ContentAssistTest.xtend

fixed tests on windows

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle

update to 2.14

---

gradle/manifest-gen.gradle

set lower guava bound to < 22

---

org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/AbstractWebServerTest.xtend
org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/AbstractXbaseWebTest.xtend

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Removed redundant modifiers

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle

[eclipse/xtext#1178] bootstrap against 2.14

[eclipse/xtext#1178] bootstrap against 2.14

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

[#60] updated node deps

---

org.eclipse.xtext.web/package-lock.json

updated package-lock.json

---

gradle/versions.gradle

updated versions to 2.16.0

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ContentAssistTest.xtend
org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/ContentAssistTest.xtend

[#81] Adapted Content Assist Changes to reflect changes in core and extras

[#81] Adapted Content Assist Changes to reflect changes in core and extras

---

org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/ContentAssistTest.xtend

Fixes failing tests introduced in eclipse/xtext-extras#345

Fix failing tests

---

gradle/versions.gradle

change version 2.16.0 -> 2.17.0

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ResourcePersistenceTest.xtend

fixed guava deprecations

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

bumped dev dep for require js

---

gradle/versions.gradle

[eclipse/xtext#1414] prepared master for version 2.18.0 

[eclipse/xtext#1414] prepared master for version 2.18.0

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/serializer/AbstractEntitiesSemanticSequencer.java
org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/serializer/AbstractEntitiesSyntacticSequencer.java
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/GenerateEntities.mwe2
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/serializer/EntitiesSemanticSequencer.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/serializer/EntitiesSyntacticSequencer.xtend
org.eclipse.xtext.web.example.statemachine/src/org/eclipse/xtext/web/example/statemachine/GenerateStatemachine.mwe2

[544435] regenerated web langs

[544435] regenerated web langs

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext-core#1077] update to gson 2.8.2

[eclipse/xtext-core#1077] update to gson 2.8.2

---

gradle/manifest-gen.gradle

Signed-off-by: Holger Schill <Holger.Schill@itemis.de>

Remove IDEA since the support has been dropped

---

gradle/upstream-repositories.gradle

replaced tf jenkins with ci.eclipse.org/xtext for lsp4j

---

1-gradle-build.sh
CBI.Jenkinsfile
gradle/java-compiler-settings.gradle

- add Slack notification
- externalized build call into shell script
- configure encoding for test execution due to encoding related test
- disable concurrent builds

[eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

---

Jenkinsfile
build.gradle
gradle/mwe2-workflows.gradle
org.eclipse.xtext.web.example.entities/build.gradle
org.eclipse.xtext.web.example.statemachine/build.gradle

Signed-off-by: Holger Schill <Holger.Schill@itemis.de>

Add option to build web samples langs with gradle #109

---

org.eclipse.xtext.web/src/test/xtext-gen/org/eclipse/xtext/web/example/statemachine/tests/StatemachineInjectorProvider.java
org.eclipse.xtext.xbase.web/src/test/xtext-gen/org/eclipse/xtext/web/example/entities/tests/EntitiesInjectorProvider.java

regenerated example languages

---

Jenkinsfile

- add Slack notification
- externalized build call into shell script

[eclipse/xtext#1384] Change to Declarative Pipeline

---

gradle/default-project-layout.gradle
org.eclipse.xtext.web.example.jetty/.classpath
org.eclipse.xtext.web.example.jetty/.project
org.eclipse.xtext.web.servlet/.classpath
org.eclipse.xtext.web.servlet/.project
org.eclipse.xtext.web/.classpath
org.eclipse.xtext.web/.project
org.eclipse.xtext.xbase.web/.classpath
org.eclipse.xtext.xbase.web/.project

[#130] fixed eclipse setup in gradle

[#130] fixed eclipse setup in gradle

---

gradle/versions.gradle

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[eclipse/xtext#1474] Prepare Master for 2.19

---

org.eclipse.xtext.web/build.gradle

switched to actively maintained fork of node gradle plugin

switched to actively maintained fork of node gradle plugin

---

org.eclipse.xtext.web.example.jetty/build.gradle
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static.html

updated jquery

---

gradle/upstream-repositories.gradle

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL

---

org.eclipse.xtext.web/build.gradle

bumped node-gradle plugin in preparation for gradle 6.0

bumped node-gradle plugin in preparation for gradle 6.0

---

org.eclipse.xtext.web/build.gradle

updated node-gradle plugin to new version 2.0

---

org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html

fixed broken requirejs version

---

Jenkinsfile
org.eclipse.xtext.web.example.jetty/build.gradle
org.eclipse.xtext.web.example.jetty/src/main/java/org/eclipse/xtext/web/example/jetty/ServerLauncher.xtend
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static.html

[#165] fixed some issues with war vs serverlauncher

[#165] fixed some issues with war vs serverlauncher

---

org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html

fixed autogenerate example

---

gradle/versions.gradle

[releng] Set version to 2.20.0

---

gradle/wrapper/gradle-wrapper.properties
gradlew
org.eclipse.xtext.web/.classpath
org.eclipse.xtext.xbase.web/.classpath

[eclipse/xtext#1520] update to gradle 5.6.1

[eclipse/xtext#1520] update to gradle 5.6.1

---

org.eclipse.xtext.web.example.entities.ide/src/org/eclipse/xtext/web/example/entities/ide/EntitiesIdeSetup.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/Entities.xtext
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/GenerateEntities.mwe2
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/formatting2/EntitiesFormatter.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/jvmmodel/EntitiesJvmModelInferrer.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/scoping/EntitiesScopeProvider.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/serializer/EntitiesSyntacticSequencer.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/validation/EntitiesValidator.xtend
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/validation/IssueCodes.java

- Add custom validation rules.
- Add custom formatting rules.
- Formatting Sourcecode.
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

[#177] Align the Xtext Entities web example to the Domainmodel example.

---

org.eclipse.xtext.web.example.jetty/build.gradle

fixed deprecated gradle code

---

org.eclipse.xtext.web/build.gradle

bumped node gradle plugin

---

gradle/eclipse-project-layout.gradle

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

---

org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/GenerateEntities.mwe2
org.eclipse.xtext.web.example.statemachine/src/org/eclipse/xtext/web/example/statemachine/GenerateStatemachine.mwe2

fixed deprecations

---

gradle/versions.gradle

[releng] Update Xtext version to 2.21.0

---

gradle/mwe2-workflows.gradle

fixed language generation

---

org.eclipse.xtext.web/build.gradle

updated node gradle plugin

---

org.eclipse.xtext.web.example.entities.ide/.classpath

restored old .classpath that was acc. changed with relicensing

---

org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/IServiceContext.java

fixed unused imports

---

gradle/versions.gradle

[releng] Update Xtext version to 2.22.0

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/parser/antlr/internal/InternalEntities.g
org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/parser/antlr/internal/InternalEntitiesParser.java

[eclipse/xtext-core#1462] Regenerated languages

[eclipse/xtext-core#1462] Regenerated languages

---

org.eclipse.xtext.web.example.jetty/src/main/webapp/style.css

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

Use consistent indentation in the web.example.jetty/style.css file.

---

gradle/versions.gradle

[releng] Update Xtext version to 2.23.0

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

use bugfixed mocha version

---

org.eclipse.xtext.web.example.jetty/.project
org.eclipse.xtext.web.example.jetty/build.gradle

[eclipse/xtext#1806] remove ModuleCoreNature

[eclipse/xtext#1806] remove ModuleCoreNature

---

gradle/versions.gradle
org.eclipse.xtext.web/build.gradle

bumped bnd and node gradle plugins

bumped bnd and node gradle plugins

---

gradle/versions.gradle

bumped bnd plugin to 5.1.2

---

gradle/mwe2-workflows.gradle
org.eclipse.xtext.web.example.entities/build.gradle
org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/GenerateEntities.mwe2
org.eclipse.xtext.web.example.statemachine/build.gradle
org.eclipse.xtext.web.example.statemachine/src/org/eclipse/xtext/web/example/statemachine/GenerateStatemachine.mwe2

fixed running workflows from gradle on windows

fixed running workflows from gradle on windows

---

gradle/versions.gradle

[releng] Update Xtext version to 2.24.0

---

org.eclipse.xtext.web.servlet/src/main/java/org/eclipse/xtext/web/servlet/XtextResourcesServlet.java

[eclipse/xtext#1850] Fix resource leaks

[eclipse/xtext#1850] Fix resource leaks

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

updated mocha (sec fixes)

---

org.eclipse.xtext.web.example.jetty/build.gradle

Download Orion via HTTPS
Fixes #117

Download Orion via HTTPS

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ContentAssistTest.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/UpdateDocumentTest.xtend
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ValidationTest.xtend

fixed junit deprecations

---

gradle/versions.gradle

bumped bnd gradle plugin

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/services/EntitiesGrammarAccess.java
org.eclipse.xtext.web.example.statemachine/src-gen/org/eclipse/xtext/web/example/statemachine/services/StatemachineGrammarAccess.java

regenerated languages

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/services/EntitiesGrammarAccess.java

regenerated test languages

---

gradle/versions.gradle

[releng] Update Xtext version to 2.25.0

---

org.eclipse.xtext.web/build.gradle

[WIP] update to node-gradle plugin 3.0.0

update to node-gradle plugin 3.0.0

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/services/EntitiesGrammarAccess.java
org.eclipse.xtext.web.example.statemachine/src-gen/org/eclipse/xtext/web/example/statemachine/services/StatemachineGrammarAccess.java

[eclipse/xtext-core#1626] regnerate languages

[eclipse/xtext-core#1626] regnerate languages

---

gradle/versions.gradle

update bnd version

---

gradle/versions.gradle

[releng] Update Xtext version to 2.26.0

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

mocha update

---

org.eclipse.xtext.web.example.jetty/build.gradle
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-static.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static-multi.html
org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static.html

update to query 3.6.0

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#1981] update to gson 2.8.7

[eclipse/xtext#1981] update to gson 2.8.7

---

org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/serializer/AbstractEntitiesSemanticSequencer.java
org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/serializer/AbstractEntitiesSyntacticSequencer.java
org.eclipse.xtext.web.example.statemachine/src-gen/org/eclipse/xtext/web/example/statemachine/serializer/StatemachineSemanticSequencer.java

[eclipse/xtext-core#1141] regen langs

[eclipse/xtext-core#1141] regen langs

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

updated mocha

---

org.eclipse.xtext.web/build.gradle

update to node 14

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#2013] update to gson 2.8.8

[eclipse/xtext#2013] update to gson 2.8.8

---

gradle/versions.gradle

update bnd plugin to 6.0.0

---

gradle/versions.gradle

update bnd plugin to 6.1.0

---

NOTICE.md

[eclipse/xtext#2020] update to classgraph 4.8.138

[eclipse/xtext#2020] update to classgraph 4.8.138

---

org.eclipse.xtext.web/build.gradle

update node gradle plugin

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#2031] update to GSON 2.8.9

[eclipse/xtext#2031] update to GSON 2.8.9

---

org.eclipse.xtext.web/build.gradle

bump node-gradle plugin to 3.2.1

bump node-gradle plugin to 3.2.1

---

gradle/versions.gradle

[releng] Update Xtext version to 2.27.0

---

gradle/versions.gradle

bump bnd gradle plugin

---

gradle/manifest-gen.gradle
org.eclipse.xtext.web.example.jetty/build.gradle

[eclipse/xtext#2028] switch to reload4j

[eclipse/xtext#2028] switch to reload4j

---

NOTICE.md

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

---

org.eclipse.xtext.web/build.gradle
org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

bump mocha

---

org.eclipse.xtext.web/build.gradle

bump gradle-node plugin

---

org.eclipse.xtext.web/build.gradle
org.eclipse.xtext.web/package-lock.json

bump node version

---

org.eclipse.xtext.web.example.entities/.settings/org.eclipse.xtend.core.Xtend.prefs
org.eclipse.xtext.web.example.statemachine/.settings/org.eclipse.xtend.core.Xtend.prefs
org.eclipse.xtext.web.servlet/.settings/org.eclipse.xtend.core.Xtend.prefs

cleanup xtend preferences

---

gradle/versions.gradle

[releng] Update Xtext version to 2.28.0

---

gradle/versions.gradle

update to bnd plugin 6.3.0

---

gradle/versions.gradle

bumped bnd tools to 6.3.1

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/GeneratorTest.java

fixed some spotbugs issues

---

NOTICE.md

[eclipse/xtext#2071] update to orbit 2022-09

[eclipse/xtext#2071] update to orbit 2022-09

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#2081] update to gson 2.9.0

[eclipse/xtext#2081] update to gson 2.9.0

---

org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/formatting2/EntitiesFormatter.java

change baseclass for xbase formatter: simplify impls

change baseclass for xbase formatter: simplify impls

---

NOTICE.md

[eclipse/xtext#2104] update to asm 9.4

[eclipse/xtext#2104] update to asm 9.4

---

org.eclipse.xtext.web.example.jetty/.project

get rid of WST

---

org.eclipse.xtext.web.example.jetty/.project

removed superflous wst nature

---

org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/AbstractWebServerTest.java
org.eclipse.xtext.xbase.web/src/test/java/org/eclipse/xtext/xbase/web/test/AbstractXbaseWebTest.java

replace File.createTempFile with Files.createTempFile.toFile

replace File.createTempFile with Files.createTempFile.toFile

---

gradle/versions.gradle

[releng] Update Xtext version to 2.30.0

---

org.eclipse.xtext.web.example.entities/model/generated/Entities.genmodel
org.eclipse.xtext.web.example.statemachine/model/generated/Statemachine.genmodel

[eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)

[eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)

---

org.eclipse.xtext.web/src/main/js/xtext/ServiceBuilder.js
org.eclipse.xtext.web/src/main/js/xtext/services/ContentAssistService.js
org.eclipse.xtext.web/src/main/js/xtext/services/FormattingService.js
org.eclipse.xtext.web/src/main/js/xtext/xtext-ace.js
org.eclipse.xtext.web/src/main/js/xtext/xtext-codemirror.js

remove nbsps from js files

---

org.eclipse.xtext.web/build.gradle
org.eclipse.xtext.web/package-lock.json

bump node plugin

---

org.eclipse.xtext.web/build.gradle

bump node gradle plugin

---

gradle/manifest-gen.gradle

[eclipse/xtext#2126] bump reload4j

[eclipse/xtext#2126] bump reload4j

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#2131] update to GSON 2.10

[eclipse/xtext#2131] update to GSON 2.10

---

org.eclipse.xtext.web.servlet/build.gradle

[eclipse/xtext#2131] update to GSON 2.10.1

[eclipse/xtext#2131] update to GSON 2.10.1 

---

gradle/versions.gradle

[releng] Update Xtext version to 2.31.0
